name: caller-scheduled

on:
  schedule:
    - cron: "* 9 * * *"

jobs:
  call-local-workflow:
    uses: dmaticzka/actions-debug-schedule-and-reusable-workflows/.github/workflows/called-workflow.yml@main
