name: simple-scheduled

on:
  schedule:
    - cron: "* 9 * * *"

jobs:
  local-workflow:
    runs-on: [ self-hosted, Linux, X64, internet-enabled ]
    steps:
      - run: echo "I'm just a simple cron"
